#!/bin/bash

# postinst
#
# Copyright (C) 2018 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in

    configure)

        # Create skeleton directories and symbolic links
        /usr/bin/kano-os-homedir-links
        ;;
        
esac

#DEBHELPER#

exit 0
